### ISSUE TITLE
Error: uninitialized constant Jasminerice

### ISSUE THREAD

**Issue by Dakuan** [bradphelan/jasminerice#108]
When I run

```
rails g jasminerice:install
```

I get:

```
[WARNING] Could not load generator "generators/jasminerice/install_generator". Error: uninitialized constant Jasminerice.
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/jasminerice-0.0.10/lib/generators/jasminerice/install_generator.rb:3:in `<top (required)>'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:300:in `block (2 levels) in lookup'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:296:in `each'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:296:in `block in lookup'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:295:in `each'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:295:in `lookup'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:152:in `find_by_namespace'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/generators.rb:169:in `invoke'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands/generate.rb:12:in `<top (required)>'
/Users/Dom/.rvm/gems/ruby-2.0.0-p0/gems/railties-3.2.12/lib/rails/commands.rb:29:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
Could not find generator jasminerice:install.
```

Im running Ruby 2.0.0 and its a regular rails app.

**Comment by adamwaite** [comment]
This is happening for me too. I'm running Ruby 2.0.0 and have a Rails 3.2.11 app.

**Comment by Dakuan** [comment]
no joy with this then?

**Comment by adamwaite** [comment]
No after a few hours of trying I sacked it off completely and just used Capybara in the end.

**Comment by jejacks0n** [comment]
@adamwaite Check out https://github.com/modeset/teabag.

I just added a commit that should fix this, but I'm encouraging folks to migrate to Teabag.
