### ISSUE TITLE
Errors when incorrectly just adding 'gem "jasminerice"' in Gemfile. Why git repo link required?

### ISSUE THREAD

**Issue by ltfschoen** [bradphelan/jasminerice#125]
As per your Readme, the correct way to add this gem to a Rails project is: 

```
group :development, :test do
  gem "jasminerice", :git => 'https://github.com/bradphelan/jasminerice.git'
end
```

Why can't we just install the gem with simply `gem "jasminerice"` (without pointing to this git repo)?

I made the mistake of copying a Gemfile from an old project of mine where I hade simply added `gem "jasminerice"` to the Gemfile. It cost me the past 10 hours trying to work that it was caused by incorrectly referring to this gem.

I was about to submit a question online, but I decided to disable each Gem to see if it got rid of the error, until I found it was because I incorrectly referenced this one. Since I already wrote most of my problem to post the question, below is my story:

In my Rails app, I generally followed the below steps to get the errors:
- Switched to Ruby 2.3.0 and associate with a Gemset

```
rvm gemset create abc_app
rvm --ruby-version use 2.3.0@abc_app
```
- Installed PSQL `rake db:create`
- Setup Devise Gem

```
rails generate devise:install
rails g devise:views users
```
- Created a Welcome Controller

```
class WelcomeController < ApplicationController
  def index
  end
end
```
- Updated Routes

```
Rails.application.routes.draw do
  root to: "welcome#index"
end
```
- Installed RSpec with `rails generate rspec:install`. No changes made to rails_helper.rb and spec_helper.rb
- If I now run `rspec`, it displays the below in terminal:

```
No examples found.
Finished in 0.00031 seconds (files took 0.08858 seconds to load)
0 examples, 0 failures
```
- I then make file app/db/seeds.rb, with the following contents

```
users = User.create!(email: 'user@abc.com', password: 'password')
```

*_Problem 1: *_When I run `rake db:seed RAILS_ENV=test`, it gives me the below ArgumentError error in console

*_Problem 2: *_When I add `require 'capybara'` in rails_helper.rb (under "add additional requires below this line"), it gives me the same ArgumentError error in console when I run `rspec`

*_Problem 3: *_When I create ../app/spec/models/user_spec.rb, and only add to it `require "rails_helper"` (without `require 'capybara'` in rails_helper.rb), it gives me the same ArgumentError error in console when I run `rspec`

*_Solution: *_Removed gem "jasminerice" from group "test" in Gemfile, and replaced with gem "jasminerice", :git => 'https://github.com/bradphelan/jasminerice.git' in group :development, :test do

**My System:**
osx yosemite - 10.10.5
rails - 4.2.6
ruby - 2.3.0p0
rspec - 3.4.4
pow

```
/Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:238:in `add_request_method': You should not use the `match` method in your router without specifying an HTTP method. (ArgumentError)
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action"
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:124:in `initialize'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:78:in `new'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:78:in `build'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:1560:in `add_route'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:1537:in `decomposed_match'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:1518:in `block in match'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:1508:in `each'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:1508:in `match'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/jasminerice-0.0.10/config/routes.rb:5:in `block in <top (required)>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:601:in `instance_exec'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:601:in `block in with_default_scope'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:817:in `scope'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:600:in `with_default_scope'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:430:in `eval_block'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:410:in `draw'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/jasminerice-0.0.10/config/routes.rb:1:in `<top (required)>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `each'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:16:in `reload!'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:26:in `block in updater'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/file_update_checker.rb:75:in `execute'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:27:in `updater'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /Users/Me/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
  from /Users/Me/code/apps/arace_app/config/environment.rb:5:in `<top (required)>'
  from /Users/Me/code/apps/arace_app/spec/rails_helper.rb:3:in `require'
  from /Users/Me/code/apps/arace_app/spec/rails_helper.rb:3:in `<top (required)>'
  from /Users/Me/code/apps/arace_app/spec/models/user_spec.rb:1:in `require'
  from /Users/Me/code/apps/arace_app/spec/models/user_spec.rb:1:in `<top (required)>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  from /Users/Me/.rvm/gems/ruby-2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `load'
  from /Users/Me/.rvm/gems/ruby-2.3.0/bin/rspec:23:in `<main>'
  from /Users/Me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/Me/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jejacks0n** [comment]
The reason is because the project is no longer maintained by the original author. At one point I made some changes to get it more up to date, and found that I had no access to release the gem so what you're asking for isn't possible given that situation. Check out other options like Teaspoon, or Konacha, etc. etc. as they're more likely to be maintained. I'm pretty sure this is covered in other issues here as well.
