### ISSUE TITLE
Unexpected token: operator (<)

### ISSUE THREAD

**Issue by jscheid** [bradphelan/jasminerice#21]
I've recently been getting the following error:

  **\* [err :: aws] Unexpected token: operator (<)
  **\* [err :: aws](in /home/application/application/releases/20111103150947/vendor/bundle/gems/jasminerice-0.0.7/app/assets/javascripts/application.js)

I think it started after upgrading to Rails 3.1.1.

Is it possible that application.js should be renamed to application.js.erb so that it will be preprocessed by ERB?

**Comment by dnagir** [comment]
I think this issue cannot be tackled at all unless you provide more information (where it happens, callstack if possible, what's your setup etc). But if the the maintainer is a magician, then he probably can figure this out :)

**Comment by jscheid** [comment]
Well, I was hoping that someone else ran into this issue before or that the error message would ring a bell.

It appears that the ERB code in application.js is not evaluated as such; googling a little seems to indicate that it would be if the file was called application.js.erb.  This is something that might have changed in Rails (Sprockets?) recently.

If nobody has any idea what the problem might be, I'm happy to spend some time and dig deeper. Out of curiosity, is anybody running jasminerice successfully on the very latest Rails version?

**Comment by dnagir** [comment]
I have no issues with the most recent Rails version, but don't use ERB in applicaiton.js.

In any case, the application.js is supposed to be the manifest only. If you want to do ERB, do it in a another file.

Also the issues doesn't seem to be related to Jasminerice as it sounds like you have problem with Sprockets with normal rails server.

**Comment by jscheid** [comment]
Sorry, I was talking about Jasminerice's application.js, this one here:

https://github.com/bradphelan/jasminerice/blob/master/app/assets/javascripts/application.js

The ERB code it contains (<% unless ... %>) seems to be the problem.

**Comment by jscheid** [comment]
(I prefer HAML over ERB and have changed a few settings in my application's Rails configuration to that end; this might have to do with it, maybe application.js is usually parsed with ERB but now is parsed with HAML? That would explain why I'm the only one having this issue.)

**Comment by dnagir** [comment]
That file should not be used at all unless you somehow require it explicitly. But I'd assume that the file should have .erb extension.

I think you can even send a pull request with this file deleted.

But it sounds like you have some config issue. I also use HAML with no issues.

**Comment by jscheid** [comment]
Thanks, Dmytrii, this is starting to make more sense.

In the meantime, here is a bit more context:

```
*** [err :: aws] /home/application/.rbenv/versions/1.9.2-p290/bin/ruby /home/application/application/releases/20111106230826/vendor/bundle/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
*** [err :: aws] 
*** [err :: aws] ** Invoke assets:precompile:all (first_time)
*** [err :: aws] 
*** [err :: aws] ** Execute assets:precompile:all
*** [err :: aws] 
*** [err :: aws] ** Invoke assets:precompile:primary (first_time)
*** [err :: aws] 
*** [err :: aws] ** Invoke assets:environment (first_time)
*** [err :: aws] 
*** [err :: aws] ** Execute assets:environment
*** [err :: aws] 
*** [err :: aws] ** Invoke environment (first_time)
*** [err :: aws] 
*** [err :: aws] ** Execute environment
*** [err :: aws] 
*** [err :: aws] Rails Error: Unable to access log file. Please ensure that /home/application/application/releases/20111106230826/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
*** [err :: aws] ** Invoke tmp:cache:clear (first_time)
*** [err :: aws] 
*** [err :: aws] ** Execute tmp:cache:clear
*** [err :: aws] ** Execute assets:precompile:primary
*** [err :: aws] rake aborted!
*** [err :: aws] 
*** [err :: aws] Unexpected token: operator (<)
*** [err :: aws] (in /home/application/application/releases/20111106230826/vendor/bundle/gems/jasminerice-0.0.7/app/assets/javascripts/application.js)
*** [err :: aws] 
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:32:in `rescue in block in eval'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:26:in `block in eval'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:78:in `block in lock'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/therubyracer-0.9.8/lib/v8/c/locker.rb:13:in `Locker'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:76:in `lock'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:25:in `eval'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/execjs-1.2.9/lib/execjs/ruby_racer_runtime.rb:17:in `exec'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/uglifier-1.0.4/lib/uglifier.rb:95:in `compile'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/actionpack-3.1.1/lib/sprockets/compressors.rb:18:in `compress'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/sprockets-2.0.3/lib/sprockets/processing.rb:265:in `block in js_compressor='
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/sprockets-2.0.3/lib/sprockets/processor.rb:29:in `call'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/sprockets-2.0.3/lib/sprockets/processor.rb:29:in `evaluate'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/sprockets-2.0.3/lib/sprockets/context.rb:175:in `block in evaluate'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/bin/rake:19:in `load'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/bin/rake:19:in `<main>'
*** [err :: aws] 
*** [err :: aws] Tasks: TOP => assets:precompile:primary
*** [err :: aws] 
*** [err :: aws] rake aborted!
*** [err :: aws] 
*** [err :: aws] Command failed with status (1): [/home/application/.rbenv/versions/1.9.2-p2...]
*** [err :: aws] 
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:53:in `block in create_shell_runner'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `call'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:45:in `sh'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `sh'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils.rb:80:in `ruby'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/file_utils_ext.rb:39:in `ruby'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/actionpack-3.1.1/lib/sprockets/assets.rake:9:in `ruby_rake_task'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/actionpack-3.1.1/lib/sprockets/assets.rake:17:in `invoke_or_reboot_rake_task'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/actionpack-3.1.1/lib/sprockets/assets.rake:25:in `block (2 levels) in <top (required)>'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
*** [err :: aws] /home/application/.rbenv/versions/1.9.2-p290/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/bin/rake:19:in `load'
*** [err :: aws] /home/application/application/releases/20111106230826/vendor/bundle/bin/rake:19:in `<main>'
*** [err :: aws] 
*** [err :: aws] Tasks: TOP => assets:precompile
*** [err :: aws] 
    command finished in 92798ms
*** [deploy:update_code] rolling back
```

I guess the problem is that Jasminerice is included in the production environment, which it doesn't need to be.  Any recommendations as to how I can exclude it from production env?  I just tried changing "gem 'jasminerice'" to "gem 'jasminerice', :group => development" in the Gemfile, but unfortunately that didn't help.

**Comment by dnagir** [comment]
1. Make sure that your `config.assets.precompile` option in Rails only includes the necessary files.
2. Exclude any non-production gems by moving it into the `group` in Gemfile (which you have already done).
3. I assume you use Capistrano. It provides the recipe that you need to `load 'deploy/assets`.
4. Ensure it works on local machine: `RAILS_ENV=production bundle exec rake assets:precompile`

**Comment by dnagir** [comment]
Again, it doesn't look like an issue with Jasminerice but rather deployment issue.
Are there any issues when you actually run Jasminerice for specs?

**Comment by jscheid** [comment]
This is working now. I am not entirely sure what fixed it, which is very frustrating. It might have been changing

```
  mount Jasminerice::Engine => "/jasmine"
```

to

```
  mount Jasminerice::Engine => "/jasmine" if Rails.env.development?
```

At any rate, it's working now without any changes to Jasminerice, so you're right it was a deployment issue. I'm closing this.

Many thanks for your help, Dmytrii, much appreciated.

**Comment by dnagir** [comment]
Glad you figured it out. But you really need to make sure it is not loaded in production rather than just unmounting the engine.

**Comment by jscheid** [comment]
Thanks. If I may take up more of your time, what do you mean by "loaded in production", why is that important, and how do I make sure it isn't loaded?

**Comment by dnagir** [comment]
You should not load any testing frameworks in production due to mirriad of reasons: decreased performance, test code affecting the production, higher memory consumption and so on.

As for the 2nd part, read on here http://gembundler.com/deploying.html

**Comment by jscheid** [comment]
Oh, I think I see the problem: my Capistrano recipe does

```
run "cd #{release_path} && bundle"
```

instead of 

```
run "cd #{release_path} && bundle --deployment"
```

Sorry, I'm still a bit new to some of this.

**Comment by dnagir** [comment]
Just use the task provided by bundler for capistrano!

**Comment by jscheid** [comment]
I will, and I'll also look into `load 'deploy/assets'`.

Once more: thanks heaps! And sorry for the noise.

**Comment by jscheid** [comment]
And just for the record: I know that test code and its dependencies has no business on a production server, I'm just not quite sure how just deploying the gem (without mounting jasmine etc.) would have an effect on memory usage -- but I'll take your word for it, and of course it's much cleaner not to deploy it in the first place.
