### ISSUE TITLE
nesting of 101 is too deep when running latest capybara/capybara webkit

### ISSUE THREAD

**Issue by noahc** [bradphelan/jasminerice#90]
I'm trying to upgrade to the latest capybara and capybara webkit. I've tried upgrading the following gems to the latest version, and even grabbing jasminerice's master branch. Below you'll find the gem versions along with the full stack trace. The tests pass and don't crash with the following:

```
gem 'capybara-webkit', '~> 0.12.1'
gem 'capybara', '~> 1.1.2'
gem 'jasmine', '~> 1.2.1'
gem 'jasminerice', '~> 0.0.10'
gem 'jasminerice-runner', '~> 0.0.3'
```

The offending setup:

```
gem 'capybara-webkit', '~> 0.14.1'
gem "capybara", "~> 2.0.2"
gem 'jasmine', '~> 1.3.1'
gem 'jasminerice', git: 'git://github.com/bradphelan/jasminerice.git'
gem 'jasminerice-runner', '~> 0.0.4'
gem "json", "~> 1.7.6"
```

And the error:

```
$ rake jasminerice:run --trace
** Invoke jasminerice:run (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute jasminerice:run
Running jasmine specsrake aborted!
nesting of 101 is too deep
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/json-1.7.6/lib/json/common.rb:155:in `parse'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/json-1.7.6/lib/json/common.rb:155:in `parse'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/capybara-webkit-        0.14.1/lib/capybara/webkit/browser.rb:148:in `evaluate_script'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/capybara-webkit-0.14.1/lib/capybara/webkit/driver.rb:50:in `evaluate_script'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/capybara-2.0.2/lib/capybara/session.rb:292:in `evaluate_script'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/jasminerice-runner-0.0.4/lib/jasminerice-runner/runner.rb:64:in `wait_for_finished'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/jasminerice-runner-0.0.4/lib/jasminerice-runner/runner.rb:18:in `run'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/jasminerice-runner-0.0.4/lib/tasks/jasminerice-runner.rake:8:in `block (2 levels) in <top (required)>'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:227:in `call'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:227:in `block in execute'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:222:in `each'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:222:in `execute'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:166:in `block in invoke_with_call_chain'
/Users/noah/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:159:in `invoke_with_call_chain'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/task.rb:152:in `invoke'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:141:in `invoke_task'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:99:in `block (2 levels) in top_level'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:99:in `each'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:99:in `block in top_level'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:108:in `run_with_threads'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:93:in `top_level'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rakegrowl-0.3.1/lib/rakegrowl.rb:33:in `top_level_with_growl'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:71:in `block in run'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:158:in `standard_exception_handling'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/lib/rake/application.rb:68:in `run'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/gems/rake-10.0.2/bin/rake:37:in `<top (required)>'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/bin/rake:19:in `load'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/bin/rake:19:in `<main>'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
/Users/noah/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => jasminerice:run
```

Any ideas on the cause of this?

**Comment by jejacks0n** [comment]
You will want to report this in the [jasminerice-runner](https://github.com/gaslight/jasminerice-runner/issues) project.. it's outside of the scope of what Jasminerice tries to do.

**Comment by andrewhavens** [comment]
In case anyone else finds this via Google (like I did)...if you are running into this error using capybara-webkit, and you are calling `evaluate_script`, and you don't need the return value after evaluating the script, try changing to use `execute_script` instead. It solved the problem for me.

**Comment by fatbeard2** [comment]
Thanks @andrewhavens!
